
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - stockshare-data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  stockshare-data:
    name: stockshare-data
